config/routes.rb
Rails.application.routes.draw do
  get 'projects/search', to: "projects#show", as: "search_project"
  get '/video', to: "projects#api"
  resources :projects do
    resources :tasks
  end
  namespace :project do
    resources :tasks
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
# gets the twitter gem that allows the twitter API to work
require 'twitter'

module Feed
  module_function

  def call(id)
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = 'An4dZgZVcata4oQYjnsSo0HRf'
      config.consumer_secret = 'bm1PctrqU8elVlNYhcuSOGAAlek8goYnfnT8XM3ois70FHml1t'
      config.access_token = '737957816359587840-rrNXjOp0Sxzgxt9pZiPyrN1ba9IQApB'
      config.access_token_secret = '5jIh5M2nu7B4Rnrcp9RNpHLRJNkIA9iyNuIYaT3ZX2v4q'
    end
    client.search("#{id} -rt", lang: 'en').take(10).each()
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  belongs_to :user

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def status
    return 'not-started' if tasks.none?

    if tasks.all? { |task| task.complete? }
      'complete'
    elsif tasks.any? { |task| task.in_progress? || task.complete? }
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    return 0 if tasks.none?
    ((total_complete.to_f / total_tasks) * 100).round
  end

  def total_complete
    tasks.select { |task| task.complete? }.count
  end

  def total_tasks
    tasks.count
  end

  def self.search(params)
    where("LOWER(name) LIKE ?", "%#{params}%")
  end

  def overdue
    date_due <= Date.today
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS =  [
    ['Not Started', 'not-started'],
    ['In Progress', 'in-progress'],
    ['Complete', 'complete']
  ]
  
  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def complete?
    status == 'complete'
  end

  def in_progress?
    status == 'in-progress'
  end

  def not_started?
    status == 'not-started'
  end
end

app/models/twitter.rb
# gets the twitter gem that allows the twitter API to work
require 'twitter'

module Twitter
  module_function

  def call
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = 'An4dZgZVcata4oQYjnsSo0HRf'
      config.consumer_secret = 'bm1PctrqU8elVlNYhcuSOGAAlek8goYnfnT8XM3ois70FHml1t'
      config.access_token = '737957816359587840-rrNXjOp0Sxzgxt9pZiPyrN1ba9IQApB'
      config.access_token_secret = '5jIh5M2nu7B4Rnrcp9RNpHLRJNkIA9iyNuIYaT3ZX2v4q'
    end
    response = client.search('#rubyonrails -rt', lang: 'en').take(5)
    response.each { |tweet| puts tweet.full_text }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/models/you_tube.rb
# gem that allows the youtube API calls
require 'yt'
require 'singleton'

module YouTube
  module_function
  class Call
    include Singleton
    Yt.configuration.api_key = 'AIzaSyDvkt2GI7OhcbAPZyjoqmynqQrp9NVk1To'

    def video
      # requesting the video via the youtube API
      response = Yt::Video.new id: 'Qq9JRO8KI1w'
      # loading the video returned from the api call
      response.embed_html
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show  edit update destroy ]
  before_action :set_video
  before_action :set_tweet

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects
    if params[:q] && !params[:q].empty?
      @projects = @projects.search(params[:q].downcase)
    end
    if params[:id] && !params[:id].empty?
      @tweet = Feed.call(params[:id].downcase)
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
    @task = @project.tasks.build
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
    # Assuming when the project is edited this method is called
    # can I just call my observer class.method here?
    # and if so how would I do that if the other class is in
    # ../observer/project_observer.rb
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # getting the projects based on id or name of the project
  def set_project
    @project = current_user.projects.find_by_id(params[:id]) || current_user.projects.find_by_name(params[:name])
  end

  # getting the API response from youtube
  def set_video
    @video = YouTube::Call.instance.video.html_safe
  end

  # getting the API response from twitter
  def set_tweet
    @tweet = Feed.call("rubyonrails".downcase)
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :date_due, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to(@task.project)
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update(task_params)
      redirect_to(@task.project)
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :project_id, :due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-center text-white">
  <div class="container">
    <div class="text-center p-3">
      © 2021 Copyright:
      <a class="text-white" href="https://github.com/Georgeking97/ProjectWebsite">George King</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="container mb-2">
  <nav class="navbar navbar-dark bg-dark">

    <a class="navbar-brand" href="<%= projects_path %>">
      <h2>Progrance</h2>
    </a>

    <form class="form-inline">
      <%= form_tag("/projects", method: 'get') do %>
        <%= text_field_tag :q, "", class: 'form-control mr-sm-2', placeholder: 'Search for projects...' %>
        <%= submit_tag("Search", class: "btn btn-secondary") %>
      <% end %>
      <div class="test">
        <% if user_signed_in? %>
          <%= link_to raw("<i class=\"fas fa-chess-pawn\"></i>"), edit_user_registration_path, :class => 'btn btn-dark' %>
          |
          <%= link_to raw("<i class=\"fas fa-sign-out-alt\"></i>"), destroy_user_session_path, method: :delete, :class => 'btn btn-dark' %>
        <% else %>
          <%= link_to raw("<i class=\"fas fa-user-plus\"></i>"), new_user_registration_path, :class => 'btn btn-dark' %> |
          <%= link_to raw("<i class=\"fas fa-sign-out-alt\"></i>"), new_user_session_path, :class => 'btn btn-dark' %>
        <% end %>
      </div>
    </form>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Progrance</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://kit.fontawesome.com/2ec2a30cc1.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<div class="main-container">
  <body class='bg-secondary'>
  <div id="header">
    <%= render partial: 'layouts/header' %>
  </div>
  <div id="body">
    <div class="container">
      <%= yield %>
    </div>
  </div>
  <div id="footer">
    <%= render partial: 'layouts/footer' %>
  </div>
  </body>
</div>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date_due %>
    <%= form.text_field :date_due,
                       data: {
                         controller: "flatpickr",
                         flatpickr_date_format: "d-m-Y",
                         flatpickr_min_date: Time.zone.now
                       }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">

    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>Editing Project</span>
    </h2>

    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/error.html.erb
<h1> ERROR, Should have searched by exact name, obviously best practice</h1>

app/views/projects/index.html.erb
<div class="sidenav">
  <div class="card">
    <div class="card-body">
      <h2>See tweets!</h2>
      <%= form_tag("/projects", method: 'get') do %>
        <div class="test mb-1">
          <%= text_field_tag :id, "", class: 'form-control mr-sm-2', placeholder: 'Search for tweets...' %>
        </div>
        <div class="test">
          <%= submit_tag("Search", class: "btn btn-dark") %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="scroll">
    <% @tweet.each do |tweet| %>
      <div class="card project-card mb-1">
        <div class="card-body">
          <%= tweet.full_text %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="card mb-2">
  <div class="card-body">
    <h2 class="card-title d-flex justify-content-between mb-4">
      <span>Projects</span>
      <%= link_to 'New Project', new_project_path, class: "btn btn-dark" %>
    </h2>

    <% if @projects.empty? %>
      <div class="card project-card mb-3">
        <div class="card-body">
          <h2>No projects created yet!</h2>
        </div>
      </div>
    <% else %>
      <% @projects.each do |project| %>
        <%= link_to project, class: 'text-decoration-none' do %>
          <div class="card project-card mb-3">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <div class="project-status">
              <span class="badge badge-<%= project.badge_color %> mb-3">
              <%= project.status %>
              </span>
                  <span class='text-secondary'>
                <small>
                  <%= project.percent_complete %>% complete
                  (<%= project.total_complete %>/<%= project.total_tasks %> tasks) ||
                  <% if project.date_due.nil? %>
                    No due date has been set
                  <% else %>
                    Due at: <%= project.date_due.strftime("%d-%m-%Y") %>
                    <% if project.overdue %>
                      <h3 style="color: #730E15"> Overdue! </h3>
                    <% end %>
                  <% end %>
                </small>
              </span>
                </div>
                <div>
                  <%= link_to 'Edit', edit_project_path(project.id), class: 'btn btn-secondary' %>
                  <%= link_to 'Destroy', project, method: :delete, class: 'btn btn-dark', data: { confirm: 'Are you sure?' } %>
                </div>
              </div>
              <h5 class="card-title text-dark"><b><%= project.name %></b></h5>
              <% if project.description.empty? %>
                <p>No description has been set</p>
              <% else %>
                <p><%= project.description %></p>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h2>
      <h2>
        Want to improve your projects? Watch below!
      </h2>
    </h2>
    <div class="card project-card mb-3">
      <div class="card-body">
        <div class="embed-responsive embed-responsive-21by9">
          <%= @video %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>New Project</span>
    </h2>

    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title d-flex justify-content-between mb-4">
      <span><%= @project.name %></span>
      <div>
        <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-secondary' %>
        <%= link_to 'Destroy', @project, method: :delete, class: 'btn btn-dark', data: { confirm: 'Are you sure?' } %>
      </div>
    </h2>

    <div class="mb-4">
      <h6>Add task</h6>
      <%= form_with(model: [@task.project, @task]) do |f| %>
        <% if @task.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
            <ul>
              <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.hidden_field :status, value: 'not-started' %>
        <div class="input-group">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Enter task name...' %>
          <div class="input-group-append">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>

    <h4>Tasks</h4>
    <div data-controller="tasks">
      <ul id='tasks-list' data-action="drop->tasks#sort">
        <% @project.tasks.order(position: :asc).each do |task| %>
          <% if task.persisted? %>
            <li class="task-item" data-task-id="<%= task.id %>">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="d-flex justify-content-between">
                    <div class='task-status'>
                      <i class="fas fa-grip-vertical grip text-secondary mr-1"></i>
                      <span class="badge badge-<%= task.badge_color %> mb-3"><%= task.status %></span>
                      <% if task.due_date.nil? %>
                        <small class="text-secondary"> No due date has been set </small>
                      <% else %>
                        <small class="text-secondary"> Due at: <%= task.due_date.strftime("%d-%m-%Y") %> </small>
                      <% end %>
                    </div>
                    <div>
                      <%= link_to 'Edit', edit_project_task_path(task.project, task), class: 'btn btn-secondary btn-sm' %>
                      <%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-dark btn-sm' %>
                    </div>
                  </div>
                  <h5 class="card-title mb-2">
                    <span><%= task.name %></span>
                  </h5>
                  <% if task.description.nil? %>
                    <p>No description has been set</p>
                  <% else %>
                    <p><%= task.description %></p>
                  <% end %>
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :due_date %>
    <%= f.text_field :due_date,
                    data: {
                      controller: "flatpickr",
                      flatpickr_date_format: "d-m-Y",
                      flatpickr_min_date: Time.zone.now
                    }, class: 'form-control' %>
  </div>
  <div class="form-group mb-3">
    <%= f.label :status %><br />
    <%= f.select :status, Task::STATUS_OPTIONS, {}, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>Editing Task</span>
    </h2>

    <%= render 'form' %>
  </div>
</div>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.description %></td>
      <td><%= task.status %></td>
      <td><%= task.project %></td>
      <td><%= link_to 'Show', [task.project, task] %></td>
      <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
      <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project %>
</p>


<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>